#lang racketscript

(require "./utils.rkt")

(provide cluster-stories)

(define (cluster-stories stories [threshold 0.4])
  (define items stories)
  (define n (items.length))
  (define used (new Set))
  (define clusters (array))
  (for ([i (in-range n)])
    (when (not (.has used i))
      (define seed (items i))
      (define members (array seed))
      (.add used i)
      (for ([j (in-range (+ i 1) n)])
        (when (not (.has used j))
          (define cand (items j))
          (define sim (jaccard-tokens (or (ref seed "rawTitleNorm") (string-downcase (or (ref seed "title") "")))
                                      (or (ref cand "rawTitleNorm") (string-downcase (or (ref cand "title") "")))))
          (when (>= sim threshold)
            (members.push cand)
            (.add used j))))
      (clusters.push (object "members" members "size" (members.length)))))
  clusters)